# Kubernetes Deployment Configuration

apiVersion: v1
kind: Namespace
metadata:
  name: sdn-nidps

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sdn-nidps-config
  namespace: sdn-nidps
data:
  system_config.yaml: |
    controller:
      worker_threads: 4
      flow_table_size: 10000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdn-controller
  namespace: sdn-nidps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sdn-controller
  template:
    metadata:
      labels:
        app: sdn-controller
    spec:
      containers:
      - name: sdn-controller
        image: sdn-nidps:latest
        ports:
        - containerPort: 6653
          name: openflow
        - containerPort: 8080
          name: wsapi
        resources:
          requests:
            cpu: "2000m"
            memory: "2Gi"
          limits:
            cpu: "4000m"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: sdn-controller-service
  namespace: sdn-nidps
spec:
  selector:
    app: sdn-controller
  ports:
  - name: openflow
    port: 6653
    targetPort: 6653
  - name: wsapi
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: sdn-nidps
spec:
  serviceName: redis-cluster
  replicas: 3
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
